### Configuration for candy snapscreen (KDE Spectacle)

OUTPUT="~/Screenshots"      # output directory
FILENAME="Snapshot"         # filename prefix
EXT="jpg"                   # image extension / format
WINDOWMODE="active"         # active | undercursor  (for -t w)
PLAYSOUND="false"           # true | false  shutter sound
CLIPBOARD="false"           # true | false  copy image to clipboard
ADITIONALPARAMS=""          # extra args passed to spectacle
